# This code reads mask from csv file and saves it in the h5 file of the DLC in a format that is readable and presentable in DLC Gui

Note: some errors might occur with h5 file in targettrack conda environment but not in the deeplabcut environment

Note: each step uses the csv file of the previous step. If you skip a step change the directory of csv file in the next step accordingly.
1. In this script you can fill the gaps in the csv file for the missing frames (where the skletonization script didn't return valid point masks)
2. You could change the number of points on the skleton of the worm
3. Copy the .h5 and .csv file generated by deeplabcut and edit it here using the skletonization results

In [1]:
import os
import sys
import csv
import numpy as np
import h5py
import pandas as pd
import datetime
from matplotlib import style
import matplotlib.pyplot as plt
from scipy.interpolate import interp1d
import copy

# 1. Steps to correct the  csv file after skletonization if some frames are missing
Use the file generated by `B1_ConvertSAM2DLC/ConvertToSkleton/skletonize.ipynb` script called `results.csv`

In [ ]:
csvFile_address = '/mnt/DATA/Mahsa/movies/LongRecordings/2025_03_19/sklet2DLC/results.csv'
csvFile_Out = csvFile_address.split(".")
csvFile_Out = csvFile_Out[0]
rows,rowsArr_float = extract_coordinates(csvFile_address,numx=0,numy=0)#numx=3,numy=1)

In [9]:
#find the frames where the skleton is missing
length = 11900# real number of frames
existence = np.ones((length))
for t in range(len(rows)):
    string = rows[t][0]
    ind = int(string)
    existence[ind] = 0

In [11]:
#add zero for skleton of missing frames
for i in np.nonzero(existence)[0]:
    if i==0:
        vector = np.full(205, '    0')
        # Set the first entry to 10
        vector[0] = str(int(i))
        rows.insert(0,vector)
    if i>0:
        search = str(i-1)
        index = int(check_strings_in_csv(rows, search))+1# find which row to place the nan row
        vector = np.full(205, '    0')
        # Set the first entry to 0
        vector[0] = str(int(i))
        rows.insert(index,vector)

ind: 0
0
ind: 1
1
ind: 2
2
ind: 3
3
ind: 4
4
ind: 5
5
ind: 6
6
ind: 7
7
ind: 8
8
ind: 9
9
ind: 10
10
ind: 11
11
ind: 12
12
ind: 13
13
ind: 14
14
ind: 15
15
ind: 16
16
ind: 17
17
ind: 18
18
ind: 19
19
ind: 20
20
ind: 21
21
ind: 22
22
ind: 23
23
ind: 24
24
ind: 25
25
ind: 26
26
ind: 27
27
ind: 28
28
ind: 29
29
ind: 30
30
ind: 31
31
ind: 32
32
ind: 33
33
ind: 34
34
ind: 35
35
ind: 36
36
ind: 37
37
ind: 38
38
ind: 39
39
ind: 40
40
ind: 41
41
ind: 42
42
ind: 43
43
ind: 44
44
ind: 45
45
ind: 46
46
ind: 47
47
ind: 48
48
ind: 49
49
ind: 50
50
ind: 51
51
ind: 52
52
ind: 53
53
ind: 54
54
ind: 55
55
ind: 56
56
ind: 57
57
ind: 58
58
ind: 59
59
ind: 60
60
ind: 61
61
ind: 62
62
ind: 63
63
ind: 64
64
ind: 65
65
ind: 66
66
ind: 67
67
ind: 68
68
ind: 69
69
ind: 70
70
ind: 71
71
ind: 72
72
ind: 73
73
ind: 74
74
ind: 75
75
ind: 76
76
ind: 77
77
ind: 78
78
ind: 79
79
ind: 80
80
ind: 81
81
ind: 82
82
ind: 83
83
ind: 84
84
ind: 85
85
ind: 86
86
ind: 87
87
ind: 88
88
ind: 89
89
ind: 172
172
ind: 185
185
ind: 370
370
ind: 478
478
ind: 483
483
ind: 498
498
ind: 499
499
ind: 506
506
ind: 898
898
ind: 900
900
ind: 901
901
ind: 902
902
ind: 903
903
ind: 904
904
ind: 905
905
ind: 906
906
ind: 907
907
ind: 911
911
ind: 914
914
ind: 916
916
ind: 917
917
ind: 919
919
ind: 920
920
ind: 927
927
ind: 928
928
ind: 929
929
ind: 930
930
ind: 931
931
ind: 932
932
ind: 933
933
ind: 934
934
ind: 935
935
ind: 936
936
ind: 937
937
ind: 938
938
ind: 939
939
ind: 940
940
ind: 941
941
ind: 942
942
ind: 943
943
ind: 944
944
ind: 945
945
ind: 946
946
ind: 947
947
ind: 948
948
ind: 949
949
ind: 950
950
ind: 951
951
ind: 952
952
ind: 953
953
ind: 954
954
ind: 955
955
ind: 956
956
ind: 957
957
ind: 958
958
ind: 959
959
ind: 960
960
ind: 961
961
ind: 962
962
ind: 963
963
ind: 964
964
ind: 965
965
ind: 966
966
ind: 967
967
ind: 968
968
ind: 969
969
ind: 970
970
ind: 971
971
ind: 972
972
ind: 973
973
ind: 974
974
ind: 975
975
ind: 976
976
ind: 977
977
ind: 978
978
ind: 979
979
ind: 1106
1106
ind: 1110
1110
ind: 1112
1112
ind: 1113
1113
ind: 1116
1116
ind: 1117
1117
ind: 1118
1118
ind: 1119
1119
ind: 1120
1120
ind: 1121
1121
ind: 1122
1122
ind: 1123
1123
ind: 1124
1124
ind: 1125
1125
ind: 1126
1126
ind: 1127
1127
ind: 1128
1128
ind: 1129
1129
ind: 1130
1130
ind: 1131
1131
ind: 1132
1132
ind: 1133
1133
ind: 1134
1134
ind: 1135
1135
ind: 1136
1136
ind: 1137
1137
ind: 1138
1138
ind: 1139
1139
ind: 1140
1140
ind: 1141
1141
ind: 1142
1142
ind: 1143
1143
ind: 1144
1144
ind: 1145
1145
ind: 1146
1146
ind: 1147
1147
ind: 1148
1148
ind: 1149
1149
ind: 1150
1150
ind: 1151
1151
ind: 1152
1152
ind: 1153
1153
ind: 1154
1154
ind: 1155
1155
ind: 1156
1156
ind: 1157
1157
ind: 1158
1158
ind: 1159
1159
ind: 1160
1160
ind: 1161
1161
ind: 1162
1162
ind: 1163
1163
ind: 1164
1164
ind: 1165
1165
ind: 1166
1166
ind: 1167
1167
ind: 1168
1168
ind: 1169
1169
ind: 1170
1170
ind: 1171
1171
ind: 1172
1172
ind: 1173
1173
ind: 1174
1174
ind: 1175
1175
ind: 1176
1176
ind: 1177
1177
ind: 1178
1178
ind: 1179
1179
ind: 1180
1180
ind: 1181
1181
ind: 1182
1182
ind: 1183
1183
ind: 1184
1184
ind: 1185
1185
ind: 1186
1186
ind: 1187
1187
ind: 1188
1188
ind: 1190
1190
ind: 1191
1191
ind: 1192
1192
ind: 1193
1193
ind: 1194
1194
ind: 1195
1195
ind: 1196
1196
ind: 1197
1197
ind: 1198
1198
ind: 1199
1199
ind: 1200
1200
ind: 1201
1201
ind: 1202
1202
ind: 1203
1203
ind: 1204
1204
ind: 1205
1205
ind: 1206
1206
ind: 1207
1207
ind: 1208
1208
ind: 1209
1209
ind: 1210
1210
ind: 1211
1211
ind: 1212
1212
ind: 1213
1213
ind: 1214
1214
ind: 1215
1215
ind: 1216
1216
ind: 1217
1217
ind: 1218
1218
ind: 1219
1219
ind: 1220
1220
ind: 1221
1221
ind: 1222
1222
ind: 1223
1223
ind: 1224
1224
ind: 1225
1225
ind: 1226
1226
ind: 1227
1227
ind: 1228
1228
ind: 1229
1229
ind: 1230
1230
ind: 1231
1231
ind: 1232
1232
ind: 1233
1233
ind: 1234
1234
ind: 1235
1235
ind: 1236
1236
ind: 1237
1237
ind: 1238
1238
ind: 1239
1239
ind: 1240
1240
ind: 1241
1241
ind: 1242
1242
ind: 1243
1243
ind: 1244
1244
ind: 1245
1245
ind: 1246
1246
ind: 1247
1247
ind: 1248
1248
ind: 1249
1249
ind: 1250
1250
ind: 1251
1251
ind: 1254
1254
ind: 1255
1255
ind: 1256
1256
ind: 1257
1257
ind: 1258
1258
ind: 1259
1259
ind: 1260
1260
ind: 1261
1261
ind: 1262
1262
ind: 1263
1263
ind: 1264
1264
ind: 1265
1265
ind: 1267
1267
ind: 1273
1273
ind: 1274
1274
ind: 1278
1278
ind: 1279
1279
ind: 1280
1280
ind: 1281
1281
ind: 1282
1282
ind: 1283
1283
ind: 1284
1284
ind: 1285
1285
ind: 1286
1286
ind: 1287
1287
ind: 1288
1288
ind: 1289
1289
ind: 1290
1290
ind: 1291
1291
ind: 1292
1292
ind: 1293
1293
ind: 1294
1294
ind: 1295
1295
ind: 1296
1296
ind: 1297
1297
ind: 1298
1298
ind: 1299
1299
ind: 1300
1300
ind: 1301
1301
ind: 1302
1302
ind: 1303
1303
ind: 1304
1304
ind: 1305
1305
ind: 1306
1306
ind: 1307
1307
ind: 1308
1308
ind: 1309
1309
ind: 1310
1310
ind: 1311
1311
ind: 1312
1312
ind: 1313
1313
ind: 1314
1314
ind: 1315
1315
ind: 1316
1316
ind: 1317
1317
ind: 1318
1318
ind: 1319
1319
ind: 1320
1320
ind: 1321
1321
ind: 1322
1322
ind: 1323
1323
ind: 1324
1324
ind: 1325
1325
ind: 1326
1326
ind: 1327
1327
ind: 1328
1328
ind: 1329
1329
ind: 1330
1330
ind: 1331
1331
ind: 1332
1332
ind: 1333
1333
ind: 1334
1334
ind: 1335
1335
ind: 1350
1350
ind: 1354
1354
ind: 1359
1359
ind: 1360
1360
ind: 1361
1361
ind: 1420
1420
ind: 1446
1446
ind: 1447
1447
ind: 1448
1448
ind: 1449
1449
ind: 1450
1450
ind: 1451
1451
ind: 1452
1452
ind: 1453
1453
ind: 1454
1454
ind: 1455
1455
ind: 1456
1456
ind: 1457
1457
ind: 1458
1458
ind: 1530
1530
ind: 1531
1531
ind: 1532
1532
ind: 1533
1533
ind: 1534
1534
ind: 1535
1535
ind: 1536
1536
ind: 1537
1537
ind: 1538
1538
ind: 1539
1539
ind: 1540
1540
ind: 1541
1541
ind: 1542
1542
ind: 1543
1543
ind: 1544
1544
ind: 1545
1545
ind: 1546
1546
ind: 1547
1547
ind: 1548
1548
ind: 1549
1549
ind: 1550
1550
ind: 1551
1551
ind: 1552
1552
ind: 1553
1553
ind: 1554
1554
ind: 1555
1555
ind: 1556
1556
ind: 1557
1557
ind: 1558
1558
ind: 1559
1559
ind: 1560
1560
ind: 1561
1561
ind: 1564
1564
ind: 1565
1565
ind: 1566
1566
ind: 1567
1567
ind: 1568
1568
ind: 1569
1569
ind: 1570
1570
ind: 1571
1571
ind: 1572
1572
ind: 1573
1573
ind: 1574
1574
ind: 1575
1575
ind: 1576
1576
ind: 1577
1577
ind: 1578
1578
ind: 1579
1579
ind: 1580
1580
ind: 1581
1581
ind: 1582
1582
ind: 1583
1583
ind: 1584
1584
ind: 1585
1585
ind: 1586
1586
ind: 1587
1587
ind: 1588
1588
ind: 1589
1589
ind: 1590
1590
ind: 1591
1591
ind: 1592
1592
ind: 1593
1593
ind: 1594
1594
ind: 1595
1595
ind: 1596
1596
ind: 1597
1597
ind: 1598
1598
ind: 1599
1599
ind: 1600
1600
ind: 1601
1601
ind: 1602
1602
ind: 1603
1603
ind: 1604
1604
ind: 1606
1606
ind: 1607
1607
ind: 1608
1608
ind: 1609
1609
ind: 1610
1610
ind: 1611
1611
ind: 1612
1612
ind: 1613
1613
ind: 1614
1614
ind: 1615
1615
ind: 1616
1616
ind: 1617
1617
ind: 1618
1618
ind: 1619
1619
ind: 1620
1620
ind: 1621
1621
ind: 1622
1622
ind: 1623
1623
ind: 1624
1624
ind: 1625
1625
ind: 1626
1626
ind: 1627
1627
ind: 1628
1628
ind: 1629
1629
ind: 1630
1630
ind: 1631
1631
ind: 1632
1632
ind: 1633
1633
ind: 1634
1634
ind: 1635
1635
ind: 1636
1636
ind: 1637
1637
ind: 1638
1638
ind: 1639
1639
ind: 1640
1640
ind: 1641
1641
ind: 1642
1642
ind: 1643
1643
ind: 1644
1644
ind: 1645
1645
ind: 1646
1646
ind: 1647
1647
ind: 1648
1648
ind: 1649
1649
ind: 1650
1650
ind: 1651
1651
ind: 1652
1652
ind: 1653
1653
ind: 1654
1654
ind: 1655
1655
ind: 1656
1656
ind: 1657
1657
ind: 1658
1658
ind: 1659
1659
ind: 1660
1660
ind: 1661
1661
ind: 1662
1662
ind: 1663
1663
ind: 1664
1664
ind: 1665
1665
ind: 1666
1666
ind: 1667
1667
ind: 1668
1668
ind: 1669
1669
ind: 1670
1670
ind: 1671
1671
ind: 1672
1672
ind: 1673
1673
ind: 1675
1675
ind: 1676
1676
ind: 1677
1677
ind: 1678
1678
ind: 1760
1760
ind: 1761
1761
ind: 1826
1826
ind: 1841
1841
ind: 1851
1851
ind: 1852
1852
ind: 1853
1853
ind: 1854
1854
ind: 1863
1863
ind: 1868
1868
ind: 2029
2029
ind: 2031
2031
ind: 2055
2055
ind: 2056
2056
ind: 2057
2057
ind: 2058
2058
ind: 2059
2059
ind: 2060
2060
ind: 2061
2061
ind: 2062
2062
ind: 2063
2063
ind: 2064
2064
ind: 2065
2065
ind: 2066
2066
ind: 2196
2196
ind: 2341
2341
ind: 2342
2342
ind: 2343
2343
ind: 2361
2361
ind: 2379
2379
ind: 2394
2394
ind: 2395
2395
ind: 2399
2399
ind: 2503
2503
ind: 2504
2504
ind: 2590
2590
ind: 2612
2612
ind: 2613
2613
ind: 2614
2614
ind: 2615
2615
ind: 2616
2616
ind: 2617
2617
ind: 2618
2618
ind: 2619
2619
ind: 2620
2620
ind: 2621
2621
ind: 2645
2645
ind: 2646
2646
ind: 2647
2647
ind: 2648
2648
ind: 2649
2649
ind: 2650
2650
ind: 2651
2651
ind: 2652
2652
ind: 2653
2653
ind: 2654
2654
ind: 2655
2655
ind: 2656
2656
ind: 2657
2657
ind: 2658
2658
ind: 2659
2659
ind: 2660
2660
ind: 2661
2661
ind: 2662
2662
ind: 2663
2663
ind: 2664
2664
ind: 2665
2665
ind: 2666
2666
ind: 2667
2667
ind: 2668
2668
ind: 2670
2670
ind: 2672
2672
ind: 2725
2725
ind: 2729
2729
ind: 2730
2730
ind: 2731
2731
ind: 2773
2773
ind: 2774
2774
ind: 2775
2775
ind: 2776
2776
ind: 2777
2777
ind: 2778
2778
ind: 2779
2779
ind: 2780
2780
ind: 2781
2781
ind: 2782
2782
ind: 2783
2783
ind: 2784
2784
ind: 2793
2793
ind: 2794
2794
ind: 2795
2795
ind: 2796
2796
ind: 2797
2797

ind: 2798
2798
ind: 2799
2799
ind: 2800
2800
ind: 2801
2801
ind: 2802
2802
ind: 2811
2811
ind: 2812
2812
ind: 2813
2813
ind: 2814
2814
ind: 2815
2815
ind: 2816
2816
ind: 2817
2817
ind: 2818
2818
ind: 2819
2819
ind: 2820
2820
ind: 2821
2821
ind: 2822
2822
ind: 2823
2823
ind: 2824
2824
ind: 2825
2825
ind: 2826
2826
ind: 2827
2827
ind: 2828
2828
ind: 2829
2829
ind: 2830
2830
ind: 2831
2831
ind: 2872
2872
ind: 2873
2873
ind: 2874
2874
ind: 2875
2875
ind: 2876
2876
ind: 2883
2883
ind: 2884
2884
ind: 2885
2885
ind: 2886
2886
ind: 2887
2887
ind: 2888
2888
ind: 2889
2889
ind: 2890
2890
ind: 2891
2891
ind: 2892
2892
ind: 2893
2893
ind: 2894
2894
ind: 2895
2895
ind: 2896
2896
ind: 2897
2897
ind: 2898
2898
ind: 2899
2899
ind: 2988
2988
ind: 2989
2989
ind: 3022
3022
ind: 3023
3023
ind: 3313
3313
ind: 3314
3314
ind: 3315
3315
ind: 3316
3316
ind: 3317
3317
ind: 3318
3318
ind: 3319
3319
ind: 3320
3320
ind: 3321
3321
ind: 3322
3322
ind: 3323
3323
ind: 3324
3324
ind: 3325
3325
ind: 3326
3326
ind: 3327
3327
ind: 3328
3328
ind: 3329
3329
ind: 3330
3330
ind: 3331
3331
ind: 3332
3332
ind: 3333
3333
ind: 3334
3334
ind: 3335
3335
ind: 3336
3336
ind: 3337
3337
ind: 3338
3338
ind: 3339
3339
ind: 3340
3340
ind: 3341
3341
ind: 3342
3342
ind: 3343
3343
ind: 3344
3344
ind: 3345
3345
ind: 3346
3346
ind: 3347
3347
ind: 3348
3348
ind: 3349
3349
ind: 3350
3350
ind: 3351
3351
ind: 3352
3352
ind: 3353
3353
ind: 3380
3380
ind: 3381
3381
ind: 3382
3382
ind: 3383
3383
ind: 3384
3384
ind: 3385
3385
ind: 3386
3386
ind: 3393
3393
ind: 3394
3394
ind: 3395
3395
ind: 3427
3427
ind: 3464
3464
ind: 3465
3465
ind: 3466
3466
ind: 3501
3501
ind: 3502
3502
ind: 3503
3503
ind: 3504
3504
ind: 3505
3505
ind: 3506
3506
ind: 3507
3507
ind: 3508
3508
ind: 3509
3509
ind: 3510
3510
ind: 3511
3511
ind: 3512
3512
ind: 3513
3513
ind: 3514
3514
ind: 3515
3515
ind: 3516
3516
ind: 3517
3517
ind: 3518
3518
ind: 3519
3519
ind: 3520
3520
ind: 3521
3521
ind: 3522
3522
ind: 3523
3523
ind: 3524
3524
ind: 3525
3525
ind: 3526
3526
ind: 3527
3527
ind: 3531
3531
ind: 3532
3532
ind: 3533
3533
ind: 3534
3534
ind: 3535
3535
ind: 3536
3536
ind: 3537
3537
ind: 3538
3538
ind: 3539
3539
ind: 3540
3540
ind: 3541
3541
ind: 3542
3542
ind: 3543
3543
ind: 3544
3544
ind: 3545
3545
ind: 3546
3546
ind: 3547
3547
ind: 3548
3548
ind: 3569
3569
ind: 3584
3584
ind: 3587
3587
ind: 3590
3590
ind: 3593
3593
ind: 3594
3594
ind: 3619
3619
ind: 3620
3620
ind: 3621
3621
ind: 3622
3622
ind: 3623
3623
ind: 3624
3624
ind: 3669
3669
ind: 3670
3670
ind: 3671
3671
ind: 3672
3672
ind: 3722
3722
ind: 3723
3723
ind: 3724
3724
ind: 3725
3725
ind: 3726
3726
ind: 3727
3727
ind: 3733
3733
ind: 3746
3746
ind: 3747
3747
ind: 3748
3748
ind: 3749
3749
ind: 3750
3750
ind: 3751
3751
ind: 3802
3802
ind: 3803
3803
ind: 3807
3807
ind: 3808
3808
ind: 3809
3809
ind: 3812
3812
ind: 3813
3813
ind: 3814
3814
ind: 3815
3815
ind: 3816
3816
ind: 3817
3817
ind: 3818
3818
ind: 3819
3819
ind: 3820
3820
ind: 3821
3821
ind: 3822
3822
ind: 3823
3823
ind: 3824
3824
ind: 3825
3825
ind: 3826
3826
ind: 3827
3827
ind: 3828
3828
ind: 3829
3829
ind: 3830
3830
ind: 3831
3831
ind: 3832
3832
ind: 3833
3833
ind: 3834
3834
ind: 3835
3835
ind: 3836
3836
ind: 3837
3837
ind: 3838
3838
ind: 3839
3839
ind: 3863
3863
ind: 3866
3866
ind: 3867
3867
ind: 3877
3877
ind: 3936
3936
ind: 3937
3937
ind: 3938
3938
ind: 3939
3939
ind: 3940
3940
ind: 3941
3941
ind: 3942
3942
ind: 3943
3943
ind: 3944
3944
ind: 3945
3945
ind: 3946
3946
ind: 3947
3947
ind: 3948
3948
ind: 3949
3949
ind: 3950
3950
ind: 3951
3951
ind: 3952
3952
ind: 3953
3953
ind: 3954
3954
ind: 3955
3955
ind: 3956
3956
ind: 3958
3958
ind: 3959
3959
ind: 3960
3960
ind: 3961
3961
ind: 3962
3962
ind: 4038
4038
ind: 4039
4039
ind: 4040
4040
ind: 4041
4041
ind: 4042
4042
ind: 4043
4043
ind: 4044
4044
ind: 4045
4045
ind: 4046
4046
ind: 4047
4047
ind: 4048
4048
ind: 4049
4049
ind: 4050
4050
ind: 4051
4051
ind: 4052
4052
ind: 4053
4053
ind: 4054
4054
ind: 4055
4055
ind: 4056
4056
ind: 4115
4115
ind: 4117
4117
ind: 4118
4118
ind: 4122
4122
ind: 4126
4126
ind: 4127
4127
ind: 4140
4140
ind: 4141
4141
ind: 4142
4142
ind: 4239
4239
ind: 4759
4759
ind: 5512
5512
ind: 5519
5519
ind: 5531
5531
ind: 5561
5561
ind: 5562
5562
ind: 5563
5563
ind: 5565
5565
ind: 5567
5567
ind: 5568
5568
ind: 5682
5682
ind: 6310
6310
ind: 6523
6523
ind: 6524
6524
ind: 6527
6527
ind: 6753
6753
ind: 6766
6766
ind: 6789
6789
ind: 6794
6794
ind: 6809
6809
ind: 6856
6856
ind: 6858
6858
ind: 6859
6859
ind: 6861
6861
ind: 6862
6862
ind: 6863
6863
ind: 6873
6873
ind: 6874
6874
ind: 6875
6875
ind: 6876
6876
ind: 6877
6877
ind: 6878
6878
ind: 6879
6879
ind: 6905
6905
ind: 6906
6906
ind: 6907
6907
ind: 6908
6908
ind: 6909
6909
ind: 6910
6910
ind: 6911
6911
ind: 6912
6912
ind: 6913
6913
ind: 6914
6914
ind: 6915
6915
ind: 6916
6916
ind: 6917
6917
ind: 6918
6918
ind: 6919
6919
ind: 6921
6921
ind: 6922
6922
ind: 6924
6924
ind: 6930
6930
ind: 6982
6982
ind: 6983
6983
ind: 6985
6985
ind: 6986
6986
ind: 6987
6987
ind: 6988
6988
ind: 6991
6991
ind: 6992
6992
ind: 6993
6993
ind: 6994
6994
ind: 6996
6996
ind: 6998
6998
ind: 7116
7116
ind: 7135
7135
ind: 7137
7137
ind: 7138
7138
ind: 7177
7177
ind: 7185
7185
ind: 7186
7186
ind: 7187
7187
ind: 7189
7189
ind: 7212
7212
ind: 7220
7220
ind: 7233
7233
ind: 7237
7237
ind: 7247
7247
ind: 7275
7275
ind: 7288
7288
ind: 7325
7325
ind: 7326
7326
ind: 7327
7327
ind: 7328
7328
ind: 7329
7329
ind: 7330
7330
ind: 7331
7331
ind: 7332
7332
ind: 7333
7333
ind: 7334
7334
ind: 7335
7335
ind: 7336
7336
ind: 7337
7337
ind: 7338
7338
ind: 7339
7339
ind: 7340
7340
ind: 7341
7341
ind: 7357
7357
ind: 7363
7363
ind: 7364
7364
ind: 7367
7367
ind: 7371
7371
ind: 7372
7372
ind: 7373
7373
ind: 7374
7374
ind: 7375
7375
ind: 7376
7376
ind: 7377
7377
ind: 7378
7378
ind: 7379
7379
ind: 7380
7380
ind: 7403
7403
ind: 7404
7404
ind: 7405
7405
ind: 7406
7406
ind: 7407
7407
ind: 7410
7410
ind: 7411
7411
ind: 7412
7412
ind: 7414
7414
ind: 7415
7415
ind: 7416
7416
ind: 7418
7418
ind: 7419
7419
ind: 7422
7422
ind: 7423
7423
ind: 7424
7424
ind: 7426
7426
ind: 7427
7427
ind: 7430
7430
ind: 7431
7431
ind: 7459
7459
ind: 7466
7466
ind: 7467
7467
ind: 7475
7475
ind: 7478
7478
ind: 7482
7482
ind: 7486
7486
ind: 7490
7490
ind: 7494
7494
ind: 7498
7498
ind: 7592
7592
ind: 7593
7593
ind: 7594
7594
ind: 7595
7595
ind: 7660
7660
ind: 7692
7692
ind: 7697
7697
ind: 7709
7709
ind: 7710
7710
ind: 7711
7711
ind: 7712
7712
ind: 7713
7713
ind: 7714
7714
ind: 7715
7715
ind: 7720
7720
ind: 7723
7723
ind: 7777
7777
ind: 7781
7781
ind: 7782
7782
ind: 7785
7785
ind: 7794
7794
ind: 7796
7796
ind: 7797
7797
ind: 7798
7798
ind: 7799
7799
ind: 7915
7915
ind: 7950
7950
ind: 7954
7954
ind: 7958
7958
ind: 7962
7962
ind: 7988
7988
ind: 7989
7989
ind: 7990
7990
ind: 7991
7991
ind: 7992
7992
ind: 8312
8312
ind: 8328
8328
ind: 8329
8329
ind: 8373
8373
ind: 8374
8374
ind: 8450
8450
ind: 8481
8481
ind: 8485
8485
ind: 8579
8579
ind: 8588
8588
ind: 8589
8589
ind: 8592
8592
ind: 8594
8594
ind: 8602
8602
ind: 8606
8606
ind: 8620
8620
ind: 8621
8621
ind: 8624
8624
ind: 8625
8625
ind: 8627
8627
ind: 8872
8872
ind: 8991
8991
ind: 9003
9003
ind: 9004
9004
ind: 9005
9005
ind: 9021
9021
ind: 9022
9022
ind: 9023
9023
ind: 9024
9024
ind: 9025
9025
ind: 9026
9026
ind: 9027
9027
ind: 9028
9028
ind: 9029
9029
ind: 9030
9030
ind: 9031
9031
ind: 9032
9032
ind: 9033
9033
ind: 9034
9034
ind: 9035
9035
ind: 9036
9036
ind: 9037
9037
ind: 9038
9038
ind: 9039
9039
ind: 9040
9040
ind: 9041
9041
ind: 9042
9042
ind: 9043
9043
ind: 9044
9044
ind: 9045
9045
ind: 9046
9046
ind: 9047
9047
ind: 9048
9048
ind: 9049
9049
ind: 9050
9050
ind: 9051
9051
ind: 9052
9052
ind: 9053
9053
ind: 9054
9054
ind: 9055
9055
ind: 9056
9056
ind: 9057
9057
ind: 9058
9058
ind: 9059
9059
ind: 9060
9060
ind: 9061
9061
ind: 9062
9062
ind: 9063
9063
ind: 9064
9064
ind: 9065
9065
ind: 9066
9066
ind: 9067
9067
ind: 9068
9068
ind: 9069
9069
ind: 9070
9070
ind: 9071
9071
ind: 9072
9072
ind: 9073
9073
ind: 9074
9074
ind: 9075
9075
ind: 9076
9076
ind: 9077
9077
ind: 9078
9078
ind: 9079
9079
ind: 9080
9080
ind: 9081
9081
ind: 9082
9082
ind: 9083
9083
ind: 9084
9084
ind: 9085
9085
ind: 9086
9086
ind: 9087
9087
ind: 9088
9088
ind: 9089
9089
ind: 9090
9090
ind: 9091
9091
ind: 9092
9092
ind: 9093
9093
ind: 9094
9094
ind: 9095
9095
ind: 9096
9096
ind: 9097
9097
ind: 9098
9098
ind: 9099
9099
ind: 9100
9100
ind: 9101
9101
ind: 9102
9102
ind: 9103
9103
ind: 9104
9104
ind: 9105
9105
ind: 9106
9106
ind: 9107
9107
ind: 9108
9108
ind: 9109
9109
ind: 9110
9110
ind: 9111
9111
ind: 9112
9112
ind: 9113
9113
ind: 9114
9114
ind: 9115
9115
ind: 9116
9116
ind: 9117
9117
ind: 9118
9118
ind: 9119
9119
ind: 9120
9120
ind: 9121
9121
ind: 9122
9122
ind: 9123
9123
ind: 9124
9124
ind: 9125
9125
ind: 9126
9126
ind: 9127
9127
ind: 9128
9128
ind: 9129
9129
ind: 9130
9130
ind: 9131
9131
ind: 9132
9132
ind: 9133
9133
ind: 9134
9134
ind: 9135
9135
ind: 9136
9136
ind: 9137
9137
ind: 9138
9138
ind: 9139
9139
ind: 9140
9140
ind: 9141
9141
ind: 9142
9142
ind: 9143
9143
ind: 9144
9144
ind: 9145
9145
ind: 9146
9146
ind: 9147
9147
ind: 9148
9148
ind: 9149
9149
ind: 9150
9150
ind: 9151
9151
ind: 9152
9152
ind: 9153
9153
ind: 9154
9154
ind: 9155
9155
ind: 9156
9156
ind: 9157
9157
ind: 9158
9158
ind: 9159
9159
ind: 9160
9160
ind: 9161
9161
ind: 9162
9162
ind: 9163
9163
ind: 9164
9164
ind: 9165
9165
ind: 9166
9166
ind: 9167
9167
ind: 9168
9168
ind: 9169
9169
ind: 9170
9170
ind: 9171
9171
ind: 9172
9172
ind: 9173
9173
ind: 9174
9174
ind: 9175
9175
ind: 9176
9176
ind: 9177
9177
ind: 9178
9178
ind: 9179
9179
ind: 9180
9180
ind: 9181
9181
ind: 9182
9182
ind: 9183
9183
ind: 9184
9184
ind: 9185
9185
ind: 9186
9186
ind: 9187
9187
ind: 9188
9188
ind: 9189
9189
ind: 9190
9190
ind: 9567
9567
ind: 9574
9574
ind: 9575
9575
ind: 9576
9576
ind: 9577
9577
ind: 9578
9578
ind: 9579
9579
ind: 9614
9614
ind: 9620
9620
ind: 9621
9621
ind: 9637
9637
ind: 9638
9638
ind: 9659
9659
ind: 9681
9681
ind: 9682
9682
ind: 9717
9717
ind: 9764
9764
ind: 9765
9765
ind: 9766
9766
ind: 9767
9767
ind: 9768
9768
ind: 9769
9769
ind: 9770
9770
ind: 9771
9771
ind: 9772
9772
ind: 9773
9773
ind: 9774
9774
ind: 9775
9775
ind: 9776
9776
ind: 9777
9777
ind: 9806
9806
ind: 9807
9807
ind: 9808
9808
ind: 9809
9809
ind: 9824
9824
ind: 9825
9825
ind: 9826
9826
ind: 9827
9827
ind: 9828
9828
ind: 9892
9892

ind: 9893
9893
ind: 9894
9894
ind: 9895
9895
ind: 9896
9896
ind: 9897
9897
ind: 9898
9898
ind: 9899
9899
ind: 9900
9900
ind: 9901
9901
ind: 9902
9902
ind: 9903
9903
ind: 9904
9904
ind: 9905
9905
ind: 9906
9906
ind: 9907
9907
ind: 9908
9908
ind: 9909
9909
ind: 9910
9910
ind: 9911
9911
ind: 9919
9919
ind: 9920
9920
ind: 9946
9946
ind: 9947
9947
ind: 9948
9948
ind: 9949
9949
ind: 9950
9950
ind: 9951
9951
ind: 9952
9952
ind: 9953
9953
ind: 9954
9954
ind: 9955
9955
ind: 9956
9956
ind: 9957
9957
ind: 9958
9958
ind: 9959
9959
ind: 9960
9960
ind: 9961
9961
ind: 9962
9962
ind: 9963
9963
ind: 9964
9964
ind: 9965
9965
ind: 9966
9966
ind: 9967
9967
ind: 9968
9968
ind: 9969
9969
ind: 9970
9970
ind: 9971
9971
ind: 9972
9972
ind: 9973
9973
ind: 10109
10109
ind: 10110
10110
ind: 10111
10111
ind: 10112
10112
ind: 10113
10113
ind: 10149
10149
ind: 10150
10150
ind: 10151
10151
ind: 10152
10152
ind: 10153
10153
ind: 10154
10154
ind: 10155
10155
ind: 10156
10156
ind: 10157
10157
ind: 10158
10158
ind: 10159
10159
ind: 10160
10160
ind: 10161
10161
ind: 10162
10162
ind: 10163
10163
ind: 10164
10164
ind: 10165
10165
ind: 10166
10166
ind: 10167
10167
ind: 10168
10168
ind: 10169
10169
ind: 10170
10170
ind: 10171
10171
ind: 10173
10173
ind: 10174
10174
ind: 10175
10175
ind: 10176
10176
ind: 10177
10177
ind: 10178
10178
ind: 10179
10179
ind: 10180
10180
ind: 10181
10181
ind: 10182
10182
ind: 10183
10183
ind: 10184
10184
ind: 10185
10185
ind: 10186
10186
ind: 10187
10187
ind: 10188
10188
ind: 10228
10228
ind: 10242
10242
ind: 10246
10246
ind: 10248
10248
ind: 10249
10249
ind: 10264
10264
ind: 10295
10295
ind: 10296
10296
ind: 10297
10297
ind: 10418
10418
ind: 10476
10476
ind: 10999
10999
ind: 11001
11001
ind: 11003
11003
ind: 11038
11038
ind: 11056
11056
ind: 11057
11057
ind: 11059
11059
ind: 11060
11060
ind: 11061
11061
ind: 11062
11062
ind: 11070
11070
ind: 11106
11106
ind: 11112
11112
ind: 11114
11114
ind: 11115
11115
ind: 11155
11155
ind: 11156
11156
ind: 11166
11166
ind: 11167
11167
ind: 11169
11169
ind: 11170
11170
ind: 11176
11176
ind: 11190
11190
ind: 11191
11191
ind: 11194
11194
ind: 11198
11198
ind: 11199
11199
ind: 11201
11201
ind: 11202
11202
ind: 11205
11205
ind: 11206
11206
ind: 11209
11209
ind: 11210
11210
ind: 11214
11214
ind: 11217
11217
ind: 11220
11220
ind: 11224
11224
ind: 11361
11361
ind: 11364
11364
ind: 11365
11365
ind: 11366
11366
ind: 11435
11435
ind: 11436
11436
ind: 11437
11437
ind: 11438
11438
ind: 11439
11439
ind: 11440
11440
ind: 11441
11441
ind: 11442
11442
ind: 11443
11443
ind: 11444
11444
ind: 11445
11445
ind: 11446
11446
ind: 11447
11447
ind: 11448
11448
ind: 11449
11449
ind: 11450
11450
ind: 11451
11451
ind: 11452
11452
ind: 11453
11453
ind: 11454
11454
ind: 11455
11455
ind: 11456
11456
ind: 11457
11457
ind: 11458
11458
ind: 11459
11459
ind: 11460
11460
ind: 11461
11461
ind: 11462
11462
ind: 11463
11463
ind: 11464
11464
ind: 11465
11465
ind: 11466
11466
ind: 11467
11467
ind: 11468
11468
ind: 11469
11469
ind: 11470
11470
ind: 11471
11471
ind: 11472
11472
ind: 11473
11473
ind: 11474
11474
ind: 11475
11475
ind: 11476
11476
ind: 11477
11477
ind: 11478
11478
ind: 11479
11479
ind: 11480
11480
ind: 11481
11481
ind: 11482
11482
ind: 11483
11483
ind: 11484
11484
ind: 11485
11485
ind: 11486
11486
ind: 11487
11487
ind: 11488
11488
ind: 11489
11489
ind: 11490
11490
ind: 11491
11491
ind: 11492
11492
ind: 11493
11493
ind: 11494
11494
ind: 11495
11495
ind: 11496
11496
ind: 11497
11497
ind: 11498
11498
ind: 11499
11499
ind: 11500
11500
ind: 11501
11501
ind: 11502
11502
ind: 11503
11503
ind: 11504
11504
ind: 11505
11505
ind: 11506
11506
ind: 11507
11507
ind: 11508
11508
ind: 11509
11509
ind: 11510
11510
ind: 11511
11511
ind: 11512
11512
ind: 11513
11513
ind: 11514
11514
ind: 11515
11515
ind: 11516
11516
ind: 11517
11517
ind: 11518
11518
ind: 11519
11519
ind: 11520
11520
ind: 11521
11521
ind: 11522
11522
ind: 11523
11523
ind: 11524
11524
ind: 11525
11525
ind: 11526
11526
ind: 11527
11527
ind: 11528
11528
ind: 11529
11529
ind: 11530
11530
ind: 11531
11531
ind: 11532
11532
ind: 11533
11533
ind: 11534
11534
ind: 11535
11535
ind: 11536
11536
ind: 11537
11537
ind: 11538
11538
ind: 11539
11539
ind: 11540
11540
ind: 11541
11541
ind: 11542
11542
ind: 11543
11543
ind: 11544
11544
ind: 11545
11545
ind: 11546
11546
ind: 11547
11547
ind: 11548
11548
ind: 11549
11549
ind: 11550
11550
ind: 11551
11551
ind: 11552
11552
ind: 11553
11553
ind: 11554
11554
ind: 11555
11555
ind: 11556
11556
ind: 11557
11557
ind: 11558
11558
ind: 11559
11559
ind: 11560
11560
ind: 11561
11561
ind: 11562
11562
ind: 11563
11563
ind: 11564
11564
ind: 11565
11565
ind: 11566
11566
ind: 11567
11567
ind: 11568
11568
ind: 11569
11569
ind: 11570
11570
ind: 11571
11571
ind: 11572
11572
ind: 11573
11573
ind: 11574
11574
ind: 11575
11575
ind: 11576
11576
ind: 11577
11577
ind: 11578
11578
ind: 11579
11579
ind: 11580
11580
ind: 11581
11581
ind: 11582
11582
ind: 11583
11583
ind: 11584
11584
ind: 11585
11585
ind: 11586
11586
ind: 11587
11587
ind: 11588
11588
ind: 11589
11589
ind: 11590
11590
ind: 11591
11591
ind: 11592
11592
ind: 11593
11593
ind: 11594
11594
ind: 11595
11595
ind: 11596
11596
ind: 11597
11597
ind: 11598
11598
ind: 11599
11599
ind: 11600
11600
ind: 11601
11601
ind: 11602
11602
ind: 11603
11603
ind: 11604
11604
ind: 11605
11605
ind: 11606
11606
ind: 11607
11607
ind: 11608
11608
ind: 11609
11609
ind: 11610
11610
ind: 11611
11611
ind: 11612
11612
ind: 11613
11613
ind: 11614
11614
ind: 11615
11615
ind: 11616
11616
ind: 11617
11617
ind: 11618
11618
ind: 11619
11619
ind: 11620
11620
ind: 11621
11621
ind: 11622
11622
ind: 11623
11623
ind: 11624
11624
ind: 11625
11625
ind: 11626
11626
ind: 11627
11627
ind: 11628
11628
ind: 11629
11629
ind: 11630
11630
ind: 11631
11631
ind: 11632
11632
ind: 11633
11633
ind: 11634
11634
ind: 11635
11635
ind: 11636
11636
ind: 11637
11637
ind: 11638
11638
ind: 11639
11639
ind: 11640
11640
ind: 11641
11641
ind: 11642
11642
ind: 11643
11643
ind: 11644
11644
ind: 11645
11645
ind: 11646
11646
ind: 11647
11647
ind: 11648
11648
ind: 11649
11649
ind: 11650
11650
ind: 11651
11651
ind: 11652
11652
ind: 11653
11653
ind: 11654
11654
ind: 11655
11655
ind: 11656
11656
ind: 11895
11895
ind: 11897
11897
ind: 11898
11898

In [12]:
# save the file including point coordinates of all frames
df_corr = pd.DataFrame(rows)
df_corr.to_csv(csvFile_Out+"_corrected.csv", index=False, na_rep='NaN',header=False)

# If the length of worm less than a theshold set the coordinate to it's previous frame

In [14]:
csvFile_address0 = '/mnt/DATA/Mahsa/movies/LongRecordings/2025_03_19/sklet2DLC/results_corrected.csv'
threshold = 100
df = pd.read_csv(csvFile_address0)
for i in range(1, len(df)):
    if float(df.iloc[i, 2]) < threshold and float(df.iloc[i, 2]) > 0:
        #print(float(df.iloc[i, 2]) )
        # Replace the row with the previous row's values
        if float(df.iloc[i -1, 2]) > threshold:
             df.iloc[i, 3:] = df.iloc[i - 1, 3:]

# Save the modified DataFrame back to a new CSV file
df.to_csv(csvFile_Out+"_correctInterp.csv", index=False)

88.41230970829642
175
85.7883690714379
176
83.26161566271068
177
96.57054013735278
178
98.4499384978453
179
80.98697574164323
180
61.25173768754009
181
81.06739612717443
318
55.51535379638744
337
55.29803250351276
342
87.76667117343578
348
85.84331100665017
368
62.36017740094234
476
74.45219125610296
490
54.72660287947797
495
95.232996247015
504
60.34654387130612
505
97.4385439140557
588
91.9524001217792
604
97.41393330575764
749
99.43002286837
750
86.11005340985626
751
87.33965396565267
753
96.16153434848069
772
71.39473817221435
984
58.4821481853813
985
75.7725392503391
1266
61.12632794621012
1275
48.38456237949973
1277
95.836610712093
1418
55.28193944108478
1419
95.75146245729904
1421
55.69441647063808
1422
63.30840616825421
1423
74.21822507596255
1424
61.402623007227554
1429
90.89674668369284
1508
42.94086971204402
1529
69.70435892401812
1562
51.9810463061712
1563
91.32771980461168
1605
52.47372388228891
1674
76.27665648021132
1680
78.17711150869076
1681
76.48200006727411
1682
68.37644814131127
1683
59.47225793221885
1684
87.0360146291936
1685
81.96863588786302
1686
71.21159414701563
1738
88.54705132541737
1804
93.71457230693431
1832
90.836659501052
1855
99.52768185161128
1860
94.10651399996152
1864
74.02823734539797
1867
92.1171247598272
1876
78.27486355779261
1890
52.12839304057761
1925
88.360217155462
1926
84.39726555784307
1932
95.79077775771768
1999
83.04946907030336
2050
98.73764663044447
2085
77.62284575404558
2141
89.38139586123023
2156
96.84751178520123
2322
96.56100927473526
2383
94.07663818625376
2391
91.99409046627405
2398
52.95924769909275
2401
94.7710213562633
2468
97.58565291872326
2502
84.55220429412162
2563
58.65974570659049
2567
52.22057780210681
2610
47.39421218542202
2611
90.4184869999307
2622
49.944235849004805
2644
72.24176659180694
2723
64.48953749377571
2724
72.78574653785415
2726
97.33795744334292
2727
67.34213789496229
2728
54.06030544182854
2732
86.0517310101269
2740
90.9769863702086
2741
97.2099564158102
2742
96.99160360605607
2743
78.87280848534029
2792
80.91395663721498
2810
70.06058019124063
2845
73.55104545227469
2846
98.24225656921315
2848
81.71242333445453
2849
86.08733332503571
2850
99.77347709933244
2852
91.95385603149124
2853
49.16870021769931
2877
51.04476054839904
2878
58.51582825411579
2879
65.55361874978705
2880
93.72505611097904
2881
92.48806378976856
2882
46.433688307455
2984
92.4231414927304
2985
86.57325616866602
2992
68.33511615952663
3024
74.1009936429328
3037
74.01272686396231
3038
74.73071161866385
3046
53.51427326599697
3186
97.44017470057356
3197
66.77337887672371
3312
70.98906659557524
3355
53.407876298965846
3356
38.101200151748
3357
90.54186932034928
3360
87.58594915206187
3375
78.83225137368179
3376
57.57836315404595
3377
77.5849724549046
3378
72.50697263917148
3379
76.44989592193443
3387
95.8770710978428
3417
69.83396166298479
3428
79.43832693821557
3429
82.72251897245314
3430
84.89962016473159
3433
82.07865316971997
3434
90.60612399188774
3497
38.50937299488114
3528
56.74535233156833
3529
63.20497119757721
3530
89.10142390649787
3586
62.40536237283472
3591
79.41949771478055
3592
83.65157874010447
3612
95.38276903850208
3617
64.6515036184833
3618
79.07562021375776
3659
91.44105678283792
3673
44.868443270972136
3678
43.148577101889714
3679
48.97714777043146
3680
92.06601381521892
3689
88.30181984045409
3698
92.31908414254151
3699
83.55419215427925
3705
73.63775259548571
3721
99.3870070900084
3728
58.59274319266094
3734
99.76508819622354
3738
88.0377050209292
3744
97.22182079188327
3771
46.52785908599008
3772
92.11313800121228
3795
72.87448899855619
3806
74.48009665934092
3810
52.003393447412016
3841
50.705844201374354
3862
41.30832338100855
3864
54.99351356432778
3865
80.75208078836606
3874
64.54310984880593
3876
96.9663612432523
3886
48.09131528315381
3935
63.97345576671948
3974
56.70898600056372
3987
59.49944625898551
3988
81.56233221590738
4007
80.92929183115646
4008
99.75840221961516
4014
84.27095143393676
4015
81.62698765443533
4121
79.15597360300525
4123
96.14145299176634
4124
82.57768089851825
4125
87.72599176797618
4139
91.1464783708764
4143
50.17226875648687
4175
89.54710633247366
4176
84.30392585865701
4177
91.92497098690896
4376
88.00716296512431
4394
61.02327379388239
4440
82.96725549163543
4450
96.20252435799512
5015
86.44471892307504
5532
87.76590194777978
5552
53.84057431264993
5564
42.011365394417794
5566
79.61200645081233
5594
80.45230697180243
5595
80.83491686407291
5598
95.96394124574816
5619
47.17318066693895
5949
84.65713565056835
6160
84.70980983720912
6161
74.990341133389
6548
80.89425970212585
6749
92.78240137496292
6755
80.4794902166124
6756
71.73761795204445
6774
68.33368384591097
6781
74.36539138213631
6782
71.70928075986805
6790
67.6812699380757
6791
80.35469679518165
6840
82.7655435456087
6866
77.43623020701365
6867
83.89638327728419
6868
88.415928455034
6871
53.637182484680594
6903
81.65750486479175
6904
50.938468143963526
6920
28.03182469651432
6923
65.64341542231216
6925
81.76227766125504
6926
69.17849094948106
6927
45.37225518904685
6928
84.8871943832797
6929
64.86960134349464
6931
78.74490694049187
6932
75.13919527340394
6933
72.82457933332137
6934
80.86769822967543
6935
95.40560482300288
6936
92.95361987103546
6937
71.4202923376712
6949
81.12058601338416
6984
52.83740707446756
6989
41.999233625492856
6990
36.557354527747
6995
28.674444645420465
6997
90.72852602668124
6999
97.50299714189666
7000
87.62397107022963
7058
47.17318066693895
7139
45.51552746012919
7166
97.2878758134252
7184
45.328715055831566
7238
63.93787087159441
7239
66.19218975728808
7273
56.206572010633565
7274
86.96220895096593
7279
68.50393758496493
7280
65.94306385705987
7286
88.31868537122229
7287
91.3724918853414
7298
99.36122984899184
7300
77.12581948259844
7306
84.89149746028365
7309
63.67689633402384
7324
99.01156630763634
7349
89.75598080438465
7350
98.83768187768636
7358
40.67212106806321
7607
87.46110941564152
7623
75.8287717688935
7658
64.4077816666302
7662
95.2504654355286
7665
45.82378174482739
7666
87.20265639525414
7667
71.78545846233853
7672
77.27125397026859
7673
69.04668149012292
7674
55.90081340752484
7676
60.90402381135237
7678
89.94307556745562
7682
89.57065930450985
7683
64.63093144329004
7690
38.00531184808444
7693
58.40210901036642
7698
64.66200488454676
7703
82.63389730191872
7704
97.3615203298232
7705
41.73966800099271
7706
92.35414618946643
7707
76.73230597723176
7708
43.66824102320047
7717
54.270401446665566
7719
62.83941129709848
7721
57.89469164188219
7727
47.23608787864038
7795
81.961773155713
7801
90.1313681430453
7920
92.33697362416812
7921
88.42986109553553
7938
81.3455371708755
7942
71.85103817084591
7986
36.61965391756056
7987
77.60141888927407
8044
60.94616680618359
8201
63.941729484641904
8330
65.94706333520355
8331
63.676896334023965
8332
64.75654772232775
8333
64.97873040281831
8334
61.68399116952081
8335
61.68399116952094
8336
92.96365605472296
8354
96.44492042245196
8355
86.96950284720475
8356
95.39262648927946
8357
89.01726329198806
8358
89.42129018799957
8359
72.62727151751588
8420
99.27231843968364
8474
91.78441358141949
8530
98.24591505268548
8531
95.2321278240611
8532
96.4385168323756
8534
98.16787995194404
8535
63.51508268473111
8571
53.98046050249522
8578
56.200405710736376
8587
57.73762568899758
8591
56.03076948924955
8595
55.657364958065926
8596
72.04402461769664
8597
69.67265549337839
8598
53.190485078092514
8599
43.915599834064885
8600
64.69965362284688
8601
59.72160449063606
8605
74.31743017907944
8607
50.21984042807309
8617
78.0996321051862
8626
79.63860035295338
8628
91.5158917726006
8661
79.4314232276487
8677
60.38229602026267
8941
79.8394243886478
8965
91.2522637312573
8978
87.65329264259945
8992
72.73273695931945
8993
64.76250114090988
8996
71.2288774791105
8999
55.61591382097619
9001
86.7960920043421
9006
75.16501831146886
9007
91.65206984299512
9008
69.59230947923315
9009
75.32855255048669
9010
73.44887855598967
9011
64.40314060767379
9012
58.38620481228083
9013
65.03126083480969
9014
59.55719122367442
9015
65.71677918459771
9016
56.92895909691883
9017
57.486953786032544
9018
54.27369225898555
9019
64.72836012415243
9020
55.66261574675088
9191
90.05299087393375
9192
65.75100512819874
9229
67.1705988598518
9230
80.82704859619078
9298
87.10731702803263
9316
93.86145958409284
9317
75.6805802197064
9320
83.46122357346707
9321
87.2301474405477
9324
78.22899280758396
9325
79.89473195100939
9328
78.6164814760464
9329
69.16076086422629
9337
76.95072758284878
9340
98.70691792890128
9342
92.3608342912346
9346
90.86847103260112
9348
78.69532230580786
9350
84.19286178685773
9352
86.61461190664065
9358
84.53092518732164
9519
84.3505798945224
9580
56.583379702391504
9610
62.25675192550869
9611
80.68141123136506
9612
99.84030798508708
9613
76.18949277388674
9627

71.99967381305409
9628
86.61188473224627
9629
84.79693244732384
9630
79.65816290283776
9778
68.5255170686882
9791
50.559683230550405
9810
95.56798706503729
9857
85.99027892246926
9860
76.07228546063008
9862
91.65646884014744
9863
79.56543700326779
9873
80.36548810043813
9883
86.5043047596671
9884
91.79820556876652
9885
55.729605631761
9886
87.47591680696556
9887
76.26995952662325
9888
51.66286534411204
9890
82.77772415401766
9974
90.753621108677
9982
52.96382466293663
10017
49.20635673488992
10021
73.36600308062887
10022
87.00972450712439
10023
90.19269776085656
10055
87.53661549926768
10058
93.00819463129824
10059
81.60690027114792
10061
85.48647597065555
10062
67.82753804954304
10063
96.50090005450184
10064
77.34076886403845
10107
64.40910292404817
10108
52.9350946038433
10172
89.02467042200504
10194
96.05475997027844
10227
81.71563056340113
10235
88.73560822910787
10238
76.5474782570006
10239
84.3468680606942
10240
92.2706418976313
10244
87.2678981395077
10245
93.45862757148858
10247
86.62861389477712
10447
43.4021099298587
10455
93.7832166211494
10559
84.45287821035967
10709
93.204552019248
10939
58.9111561780258
11039
62.305552553695286
11040
55.03012258256118
11063
57.40745942247751
11064
52.19451941293767
11108
48.311014041244405
11111
72.53020292483443
11129
72.25016418158357
11152
47.5242357343408
11203
96.4612723034316
11359
54.7782467183447
11360
97.8365986714386
11362
80.09726655763022
11367
90.5142560251754
11368
96.72359128417295
11369
95.98841288476348
11370
97.74124637882184
11371
93.9994296143607
11372
91.84385530260494
11373
98.24094549761286
11374
96.76405203661518
11382
87.43948091991417
11383
90.84587228659989
11384
87.08774389794127
11385
93.06218957043554
11386
94.19081047655108
11387
84.39364509908022
11388
85.69565611785939
11389
87.16228348375665
11390
89.9693114053199
11391
91.48555591820758
11392
97.1478930475165
11393
97.00927512296884
11404
84.18474969084951
11405
96.8360167807664
11406
95.13153056201612
11407
89.29421601808389
11408
89.87617079484819
11409
95.91610478015632
11410
96.94994348784044
11412
93.13763866950212
11430
90.91330142864264
11431
84.11993941492125
11432
59.03256356818396
11433
40.61529638135345
11434
64.29553614022886
11657
90.68713041141264
11658
84.82844433868796
11659
81.7578192403567
11671

# 2. Change the number of points

In [15]:

#save different point length
df = pd.read_csv(csvFile_Out+"_correctInterp.csv")
df = df.iloc[:, 3:]

# Select every 20th column and the one after it
selected_columns = [i for i in range(0, df.shape[1], 20)] + [i + 1 for i in range(0, df.shape[1], 20)]
selected_columns = sorted(selected_columns)  # Ensure the columns are in order
df_selected = df.iloc[:, selected_columns]
df_selected.to_csv(csvFile_Out+"_11pt.csv", index=False)

# 3. Save the points in DLC format
First generate a DeepLabCut project for the movie you are analyzing. Choose all frames in DeepLabCut for labeling set.

use `CollectedData_Mahsa.h5/csv` files that are generated by DLC in labeled-data/Name_of_Avi_movie folder and make a copy of them called `CollectedData_Mahsa0.h5/csv`
Read the annotation from another .csv file, generated by skletonization script, and modify DLC files based on that. The final  `CollectedData_Mahsa.h5/csv` is the file you can visualize in DLC. Just place the resulting `CollectedData_Mahsa.h5/csv` after running the script in labeled-data/Name_of_Avi_movie directory in DLC project folder.

In [17]:
#file that contains the skleton points coordinates
csvFile_address = '/mnt/DATA/Mahsa/movies/LongRecordings/2025_03_19/sklet2DLC/results_11pt.csv'

csvFile_Out = csvFile_address.split(".")
csvFile_Out = csvFile_Out[0]

In [22]:
#CSV and H5 files created by DLC and copies of them used for saving new data
CSVDLC = '/mnt/DATA/Mahsa/movies/LongRecordings/2025_03_19/sklet2DLC/CollectedData_Mahsa.csv'
# basically a copy of the file above:
CSVDLCold = '/mnt/DATA/Mahsa/movies/LongRecordings/2025_03_19/sklet2DLC/CollectedData_Mahsa0.csv'

#HDLC should be a copy of  HDLCold in the beginning
H5DLC = '/mnt/DATA/Mahsa/movies/LongRecordings/2025_03_19/sklet2DLC/CollectedData_Mahsa.h5'

H5DLCold = '/mnt/DATA/Mahsa/movies/LongRecordings/2025_03_19/sklet2DLC/CollectedData_Mahsa0.h5'

In [23]:
hdold  = h5py.File(H5DLCold,'r')
hd  = h5py.File(H5DLC,'r+')

In [26]:
#open csv file of the annotations to check
file = open(csvFile_address)
type(file)
csvreader = csv.reader(file)
np.shape(csvreader)
rows = []

for row in csvreader:
    rows.append(row)
        
print(np.shape(rows))

(11900, 22)

## 3.1. Read csv file of annotations from another software-input from Mediar or SAM after skletonization

change numx and numy appropriatey so that 
rowsArr_float is a TxP matrix that T is the number of frames annotated and P xy coordinate of the points

In [27]:
rows,rowsArr_float = extract_coordinates(csvFile_address,numx=0,numy=0)#numx=3,numy=1)

(11900, 22)
(11900, 22)

In [28]:
#change order of x and y columns if needed
rowsArr_floatxy = copy.deepcopy(rowsArr_float)
rowsArr_floatxy[:, ::2], rowsArr_floatxy[:, 1::2] = rowsArr_float[:, 1::2], rowsArr_float[:, ::2].copy()

## 3.2. Update h5 file obtained from DLC project and close the h5 file

In [29]:
#update datasets of the h5 file to include the imported annotations
new_image_count = 11900  # Total number of frames in behavioral recording
current_length = 5  #length of imgfiles number suffix. matching DLC extracted frames. usually 5

# Generate new values for each dataset
new_axis1_level2 = np.array([f'img{str(i).zfill(current_length)}.png'.encode('utf-8') for i in range(new_image_count)])
new_axis1_label0 = np.zeros(new_image_count, dtype=int)
new_axis1_label1 = np.zeros(new_image_count, dtype=int)
new_axis1_label2 = np.arange(new_image_count)

new_coordinates = rowsArr_floatxy[:new_image_count,:].transpose()
with h5py.File(H5DLC, 'a') as h5_file:
    # Delete existing datasets if needed
    for name, data in zip(['axis1_label0', 'axis1_label1', 'axis1_label2','axis1_level2'], 
                          [new_axis1_label0, new_axis1_label1, new_axis1_label2, new_axis1_level2]):
        
        if name in h5_file['keypoints'].keys():
            del h5_file[f'keypoints/{name}']
            print("deleted")
        
        # Create new resizable datasets
        h5_file.create_dataset(f'keypoints/{name}', data=data, maxshape=(None,))
    
# Open the H5 file and update `block0_values`
with h5py.File(H5DLC, 'a') as h5_file:
    block0_values = h5_file['keypoints/block0_values']
    
     # Delete existing dataset if needed
    if 'block0_values' in h5_file['keypoints'].keys():
        del h5_file['keypoints/block0_values']

    # Create a new dataset with resizable rows
    block0_values = h5_file.create_dataset(
        'keypoints/block0_values',
        data=new_coordinates,
        maxshape=(None, new_coordinates.shape[1])  # Allows resizing along rows
    )

#updatae the attributes of datasets that you updataes
for dataname in ['axis1_label0', 'axis1_label1', 'axis1_label2','axis1_level2']:
    for attr in hdold[f'keypoints/{dataname}'].attrs.keys():
        hd[f'keypoints/{dataname}'].attrs[attr] = hdold[f'keypoints/{dataname}'].attrs[attr]

axis1_label0
<KeysViewHDF5 ['axis0_label0', 'axis0_label1', 'axis0_label2', 'axis0_level0', 'axis0_level1', 'axis0_level2', 'axis1_label0', 'axis1_label1', 'axis1_label2', 'axis1_level0', 'axis1_level1', 'axis1_level2', 'block0_items_label0', 'block0_items_label1', 'block0_items_label2', 'block0_items_level0', 'block0_items_level1', 'block0_items_level2', 'block0_values']>
deleted
axis1_label1
<KeysViewHDF5 ['axis0_label0', 'axis0_label1', 'axis0_label2', 'axis0_level0', 'axis0_level1', 'axis0_level2', 'axis1_label0', 'axis1_label1', 'axis1_label2', 'axis1_level0', 'axis1_level1', 'axis1_level2', 'block0_items_label0', 'block0_items_label1', 'block0_items_label2', 'block0_items_level0', 'block0_items_level1', 'block0_items_level2', 'block0_values']>
deleted
axis1_label2
<KeysViewHDF5 ['axis0_label0', 'axis0_label1', 'axis0_label2', 'axis0_level0', 'axis0_level1', 'axis0_level2', 'axis1_label0', 'axis1_label1', 'axis1_label2', 'axis1_level0', 'axis1_level1', 'axis1_level2', 'block0_items_label0', 'block0_items_label1', 'block0_items_label2', 'block0_items_level0', 'block0_items_level1', 'block0_items_level2', 'block0_values']>
deleted
axis1_level2
<KeysViewHDF5 ['axis0_label0', 'axis0_label1', 'axis0_label2', 'axis0_level0', 'axis0_level1', 'axis0_level2', 'axis1_label0', 'axis1_label1', 'axis1_label2', 'axis1_level0', 'axis1_level1', 'axis1_level2', 'block0_items_label0', 'block0_items_label1', 'block0_items_label2', 'block0_items_level0', 'block0_items_level1', 'block0_items_level2', 'block0_values']>
deleted
<KeysViewHDF5 ['CLASS', 'FLAVOR', 'TITLE', 'VERSION', 'transposed']>
CLASS
b'ARRAY'
FLAVOR
b'numpy'
TITLE
Empty(dtype=dtype('S1'))
VERSION
b'2.4'
transposed
1
<KeysViewHDF5 ['CLASS', 'FLAVOR', 'TITLE', 'VERSION', 'transposed']>
CLASS
b'ARRAY'
FLAVOR
b'numpy'
TITLE
Empty(dtype=dtype('S1'))
VERSION
b'2.4'
transposed
1
<KeysViewHDF5 ['CLASS', 'FLAVOR', 'TITLE', 'VERSION', 'transposed']>
CLASS
b'ARRAY'
FLAVOR
b'numpy'
TITLE
Empty(dtype=dtype('S1'))
VERSION
b'2.4'
transposed
1
<KeysViewHDF5 ['CLASS', 'FLAVOR', 'TITLE', 'VERSION', 'axis1_nameNone', 'kind', 'name', 'transposed']>
CLASS
b'ARRAY'
FLAVOR
b'numpy'
TITLE
Empty(dtype=dtype('S1'))
VERSION
b'2.4'
axis1_nameNone
b'N.'
kind
b'string'
name
b'N.'
transposed
1

In [30]:
hd.close()
hdold.close()

## Check Datasets with H5PY

In [31]:
#check datasets with h5py
with h5py.File(H5DLC, 'r') as h5_file:
    # List all groups and datasets
    def print_structure(name, obj):
        if isinstance(obj, h5py.Dataset):
            print(f"Dataset: {name}, Shape: {obj.shape}, Data Type: {obj.dtype}")
        elif isinstance(obj, h5py.Group):
            print(f"Group: {name}")

    h5_file.visititems(print_structure)

Group: keypoints
Dataset: keypoints/axis0_label0, Shape: (22,), Data Type: int8
Dataset: keypoints/axis0_label1, Shape: (22,), Data Type: int8
Dataset: keypoints/axis0_label2, Shape: (22,), Data Type: int8
Dataset: keypoints/axis0_level0, Shape: (1,), Data Type: |S5
Dataset: keypoints/axis0_level1, Shape: (11,), Data Type: |S10
Dataset: keypoints/axis0_level2, Shape: (2,), Data Type: |S1
Dataset: keypoints/axis1_label0, Shape: (11900,), Data Type: int64
Dataset: keypoints/axis1_label1, Shape: (11900,), Data Type: int64
Dataset: keypoints/axis1_label2, Shape: (11900,), Data Type: int64
Dataset: keypoints/axis1_level0, Shape: (1,), Data Type: |S12
Dataset: keypoints/axis1_level1, Shape: (1,), Data Type: |S24
Dataset: keypoints/axis1_level2, Shape: (11900,), Data Type: |S12
Dataset: keypoints/block0_items_label0, Shape: (22,), Data Type: int8
Dataset: keypoints/block0_items_label1, Shape: (22,), Data Type: int8
Dataset: keypoints/block0_items_label2, Shape: (22,), Data Type: int8
Dataset: keypoints/block0_items_level0, Shape: (1,), Data Type: |S5
Dataset: keypoints/block0_items_level1, Shape: (11,), Data Type: |S10
Dataset: keypoints/block0_items_level2, Shape: (2,), Data Type: |S1
Dataset: keypoints/block0_values, Shape: (22, 11900), Data Type: float64

## Check Datasets with panda

In [32]:
df = pd.read_hdf(H5DLCold)
df

scorer                                                   Mahsa              \
bodyparts                                            bodypart1
coords                                                       x           y
labeled-data temp-03192025191735-crop img00000.png  329.007022  241.879139
                                      img00234.png  391.244062  333.329483
                                      img00728.png  370.921763  201.234541
                                      img00729.png  372.191907  199.964397

scorer                                                                      \
bodyparts                                            bodypart2
coords                                                       x           y
labeled-data temp-03192025191735-crop img00000.png  374.732194  258.391006
                                      img00234.png  388.703775  295.225173
                                      img00728.png  387.433631  239.338851
                                      img00729.png  386.163487  239.338851

scorer                                                                      \
bodyparts                                            bodypart3
coords                                                       x           y
labeled-data temp-03192025191735-crop img00000.png  416.646935  276.173018
                                      img00234.png  383.623200  245.689570
                                      img00728.png  387.433631  282.523736
                                      img00729.png  395.054493  278.713305

scorer                                                                      \
bodyparts                                            bodypart4
coords                                                       x           y
labeled-data temp-03192025191735-crop img00000.png  454.751246  291.414742
                                      img00234.png  355.680039  219.016552
                                      img00728.png  369.651619  316.817615
                                      img00729.png  369.651619  315.547472

scorer                                                                      \
bodyparts                                            bodypart5
coords                                                       x           y
labeled-data temp-03192025191735-crop img00000.png  499.206274  283.793880
                                      img00234.png  335.357740  202.504685
                                      img00728.png  322.656304  320.628046
                                      img00729.png  348.059177  332.059339

scorer                                              ...              \
bodyparts                                           ...   bodypart7
coords                                              ...           x
labeled-data temp-03192025191735-crop img00000.png  ...  576.685038
                                      img00234.png  ...  341.708459
                                      img00728.png  ...  250.258114
                                      img00729.png  ...  257.878976

scorer                                                                      \
bodyparts                                                        bodypart8
coords                                                       y           x
labeled-data temp-03192025191735-crop img00000.png  255.850719  633.841503
                                      img00234.png  137.727357  374.732194
                                      img00728.png  346.030920  240.096965
                                      img00729.png  344.760776  240.096965

scorer                                                                      \
bodyparts                                                        bodypart9
coords                                                       y           x
labeled-data temp-03192025191735-crop img00000.png  249.500001  664.324952
                                      img00234.png  119.945346  416.646935
                                      img00728.png  387.945661  218.504522
                                      img00729.png  382.865086  227.395528

scorer                                                                      \
bodyparts                                                       bodypart10
coords                                                       y           x
labeled-data temp-03192025191735-crop img00000.png  243.149282  679.566676
                                      img00234.png  116.134915  443.319952
                                      img00728.png  420.969396  180.400212
                                      img00729.png  415.888822  208.343373

scorer                                                                      \
bodyparts                                                       bodypart11
coords                                                       y           x
labeled-data temp-03192025191735-crop img00000.png  225.367271  687.187538
                                      img00234.png  102.163335  463.642251
                                      img00728.png  461.613994  160.077913
                                      img00729.png  431.130546  179.130069

scorer
bodyparts
coords                                                       y
labeled-data temp-03192025191735-crop img00000.png  215.206121
                                      img00234.png   65.329168
                                      img00728.png  470.505000
                                      img00729.png  467.964712

[4 rows x 22 columns]

In [33]:
df = pd.read_hdf(H5DLC)#, key='your_dataset_key')  # Replace 'your_dataset_key' with the dataset name
df

scorer                                                 Mahsa         \
bodyparts                                          bodypart1
coords                                                     x      y
labeled-data temp-03192025191735-crop img00000.png       0.3    0.2
                                      img00001.png       0.0    0.0
                                      img00002.png       0.0    0.0
                                      img00003.png       0.0    0.0
                                      img00004.png       0.0    0.0
...                                                      ...    ...
                                      img11895.png     315.0  257.0
                                      img11896.png       0.0    0.0
                                      img11897.png     312.5  230.5
                                      img11898.png       0.0    0.0
                                      img11899.png       0.0    0.0

scorer                                                                      \
bodyparts                                            bodypart2
coords                                                       x           y
labeled-data temp-03192025191735-crop img00000.png    0.230000    0.220000
                                      img00001.png    0.000000    0.000000
                                      img00002.png    0.000000    0.000000
                                      img00003.png    0.000000    0.000000
                                      img00004.png    0.000000    0.000000
...                                                        ...         ...
                                      img11895.png  315.554245  220.162257
                                      img11896.png    0.000000    0.000000
                                      img11897.png  329.018898  199.876957
                                      img11898.png    0.000000    0.000000
                                      img11899.png    0.000000    0.000000

scorer                                                                      \
bodyparts                                            bodypart3
coords                                                       x           y
labeled-data temp-03192025191735-crop img00000.png    0.430000    0.420000
                                      img00001.png    0.000000    0.000000
                                      img00002.png    0.000000    0.000000
                                      img00003.png    0.000000    0.000000
                                      img00004.png    0.000000    0.000000
...                                                        ...         ...
                                      img11895.png  326.475608  185.189109
                                      img11896.png    0.000000    0.000000
                                      img11897.png  327.591610  165.014893
                                      img11898.png    0.000000    0.000000
                                      img11899.png    0.000000    0.000000

scorer                                                                      \
bodyparts                                            bodypart4
coords                                                       x           y
labeled-data temp-03192025191735-crop img00000.png    0.630000    0.620000
                                      img00001.png    0.000000    0.000000
                                      img00002.png    0.000000    0.000000
                                      img00003.png    0.000000    0.000000
                                      img00004.png    0.000000    0.000000
...                                                        ...         ...
                                      img11895.png  338.171115  150.769425
                                      img11896.png    0.000000    0.000000
                                      img11897.png  350.943654  140.552177
                                      img11898.png    0.000000    0.000000
                                      img11899.png    0.000000    0.000000

scorer                                                                      \
bodyparts                                            bodypart5
coords                                                       x           y
labeled-data temp-03192025191735-crop img00000.png    0.830000    0.820000
                                      img00001.png    0.000000    0.000000
                                      img00002.png    0.000000    0.000000
                                      img00003.png    0.000000    0.000000
                                      img00004.png    0.000000    0.000000
...                                                        ...         ...
                                      img11895.png  369.274747  129.213179
                                      img11896.png    0.000000    0.000000
                                      img11897.png  382.840803  127.459172
                                      img11898.png    0.000000    0.000000
                                      img11899.png    0.000000    0.000000

scorer                                              ...              \
bodyparts                                           ...   bodypart7
coords                                              ...           x
labeled-data temp-03192025191735-crop img00000.png  ...    0.123000
                                      img00001.png  ...    0.000000
                                      img00002.png  ...    0.000000
                                      img00003.png  ...    0.000000
                                      img00004.png  ...    0.000000
...                                                 ...         ...
                                      img11895.png  ...  430.668579
                                      img11896.png  ...    0.000000
                                      img11897.png  ...  433.732877
                                      img11898.png  ...    0.000000
                                      img11899.png  ...    0.000000

scorer                                                                      \
bodyparts                                                        bodypart8
coords                                                       y           x
labeled-data temp-03192025191735-crop img00000.png    0.122000    0.143000
                                      img00001.png    0.000000    0.000000
                                      img00002.png    0.000000    0.000000
                                      img00003.png    0.000000    0.000000
                                      img00004.png    0.000000    0.000000
...                                                        ...         ...
                                      img11895.png  155.528922  430.775114
                                      img11896.png    0.000000    0.000000
                                      img11897.png  164.094948  428.415516
                                      img11898.png    0.000000    0.000000
                                      img11899.png    0.000000    0.000000

scorer                                                                      \
bodyparts                                                        bodypart9
coords                                                       y           x
labeled-data temp-03192025191735-crop img00000.png    0.142000    0.163000
                                      img00001.png    0.000000    0.000000
                                      img00002.png    0.000000    0.000000
                                      img00003.png    0.000000    0.000000
                                      img00004.png    0.000000    0.000000
...                                                        ...         ...
                                      img11895.png  192.280060  401.072400
                                      img11896.png    0.000000    0.000000
                                      img11897.png  197.940229  397.703443
                                      img11898.png    0.000000    0.000000
                                      img11899.png    0.000000    0.000000

scorer                                                                      \
bodyparts                                                       bodypart10
coords                                                       y           x
labeled-data temp-03192025191735-crop img00000.png    0.162000    0.183000
                                      img00001.png    0.000000    0.000000
                                      img00002.png    0.000000    0.000000
                                      img00003.png    0.000000    0.000000
                                      img00004.png    0.000000    0.000000
...                                                        ...         ...
                                      img11895.png  214.052018  363.714746
                                      img11896.png    0.000000    0.000000
                                      img11897.png  210.390771  363.566778
                                      img11898.png    0.000000    0.000000
                                      img11899.png    0.000000    0.000000

scorer                                                                     \
bodyparts                                                      bodypart11
coords                                                       y          x
labeled-data temp-03192025191735-crop img00000.png    0.182000      0.203
                                      img00001.png    0.000000      0.000
                                      img00002.png    0.000000      0.000
                                      img00003.png    0.000000      0.000
                                      img00004.png    0.000000      0.000
...                                                        ...        ...
                                      img11895.png  216.825961    332.500
                                      img11896.png    0.000000      0.000
                                      img11897.png  216.188158    334.500
                                      img11898.png    0.000000      0.000
                                      img11899.png    0.000000      0.000

scorer
bodyparts
coords                                                    y
labeled-data temp-03192025191735-crop img00000.png    0.202
                                      img00001.png    0.000
                                      img00002.png    0.000
                                      img00003.png    0.000
                                      img00004.png    0.000
...                                                     ...
                                      img11895.png  233.500
                                      img11896.png    0.000
                                      img11897.png  230.500
                                      img11898.png    0.000
                                      img11899.png    0.000

[11900 rows x 22 columns]

In [8]:
inspect_h5(H5DLC)
print("**********************************************************************")
inspect_h5(H5DLCold)

Group: keypoints
Dataset: keypoints/axis0_label0, Shape: (30,), Data Type: int8
Attributes: {'CLASS': b'ARRAY', 'FLAVOR': b'numpy', 'TITLE': Empty(dtype=dtype('S1')), 'VERSION': b'2.4', 'transposed': 1}
Dataset: keypoints/axis0_label1, Shape: (30,), Data Type: int8
Attributes: {'CLASS': b'ARRAY', 'FLAVOR': b'numpy', 'TITLE': Empty(dtype=dtype('S1')), 'VERSION': b'2.4', 'transposed': 1}
Dataset: keypoints/axis0_label2, Shape: (30,), Data Type: int8
Attributes: {'CLASS': b'ARRAY', 'FLAVOR': b'numpy', 'TITLE': Empty(dtype=dtype('S1')), 'VERSION': b'2.4', 'transposed': 1}
Dataset: keypoints/axis0_level0, Shape: (1,), Data Type: |S5
Attributes: {'CLASS': b'ARRAY', 'FLAVOR': b'numpy', 'TITLE': Empty(dtype=dtype('S1')), 'VERSION': b'2.4', 'axis0_namescorer': b'scorer', 'kind': b'string', 'name': b'scorer', 'transposed': 1}
Dataset: keypoints/axis0_level1, Shape: (15,), Data Type: |S10
Attributes: {'CLASS': b'ARRAY', 'FLAVOR': b'numpy', 'TITLE': Empty(dtype=dtype('S1')), 'VERSION': b'2.4', 'axis0_namebodyparts': b'bodyparts', 'kind': b'string', 'name': b'bodyparts', 'transposed': 1}
Dataset: keypoints/axis0_level2, Shape: (2,), Data Type: |S1
Attributes: {'CLASS': b'ARRAY', 'FLAVOR': b'numpy', 'TITLE': Empty(dtype=dtype('S1')), 'VERSION': b'2.4', 'axis0_namecoords': b'coords', 'kind': b'string', 'name': b'coords', 'transposed': 1}
Dataset: keypoints/axis1_label0, Shape: (12749,), Data Type: int64
Attributes: {'CLASS': b'ARRAY', 'FLAVOR': b'numpy', 'TITLE': Empty(dtype=dtype('S1')), 'VERSION': b'2.4', 'transposed': 1}
Dataset: keypoints/axis1_label1, Shape: (12749,), Data Type: int64
Attributes: {'CLASS': b'ARRAY', 'FLAVOR': b'numpy', 'TITLE': Empty(dtype=dtype('S1')), 'VERSION': b'2.4', 'transposed': 1}
Dataset: keypoints/axis1_label2, Shape: (12749,), Data Type: int64
Attributes: {'CLASS': b'ARRAY', 'FLAVOR': b'numpy', 'TITLE': Empty(dtype=dtype('S1')), 'VERSION': b'2.4', 'transposed': 1}
Dataset: keypoints/axis1_level0, Shape: (1,), Data Type: |S12
Attributes: {'CLASS': b'ARRAY', 'FLAVOR': b'numpy', 'TITLE': Empty(dtype=dtype('S1')), 'VERSION': b'2.4', 'axis1_nameNone': b'N.', 'kind': b'string', 'name': b'N.', 'transposed': 1}
Dataset: keypoints/axis1_level1, Shape: (1,), Data Type: |S24
Attributes: {'CLASS': b'ARRAY', 'FLAVOR': b'numpy', 'TITLE': Empty(dtype=dtype('S1')), 'VERSION': b'2.4', 'axis1_nameNone': b'N.', 'kind': b'string', 'name': b'N.', 'transposed': 1}
Dataset: keypoints/axis1_level2, Shape: (12749,), Data Type: |S12
Attributes: {'CLASS': b'ARRAY', 'FLAVOR': b'numpy', 'TITLE': Empty(dtype=dtype('S1')), 'VERSION': b'2.4', 'axis1_nameNone': b'N.', 'kind': b'string', 'name': b'N.', 'transposed': 1}
Dataset: keypoints/block0_items_label0, Shape: (30,), Data Type: int8
Attributes: {'CLASS': b'ARRAY', 'FLAVOR': b'numpy', 'TITLE': Empty(dtype=dtype('S1')), 'VERSION': b'2.4', 'transposed': 1}
Dataset: keypoints/block0_items_label1, Shape: (30,), Data Type: int8
Attributes: {'CLASS': b'ARRAY', 'FLAVOR': b'numpy', 'TITLE': Empty(dtype=dtype('S1')), 'VERSION': b'2.4', 'transposed': 1}
Dataset: keypoints/block0_items_label2, Shape: (30,), Data Type: int8
Attributes: {'CLASS': b'ARRAY', 'FLAVOR': b'numpy', 'TITLE': Empty(dtype=dtype('S1')), 'VERSION': b'2.4', 'transposed': 1}
Dataset: keypoints/block0_items_level0, Shape: (1,), Data Type: |S5
Attributes: {'CLASS': b'ARRAY', 'FLAVOR': b'numpy', 'TITLE': Empty(dtype=dtype('S1')), 'VERSION': b'2.4', 'block0_items_namescorer': b'scorer', 'kind': b'string', 'name': b'scorer', 'transposed': 1}
Dataset: keypoints/block0_items_level1, Shape: (15,), Data Type: |S10
Attributes: {'CLASS': b'ARRAY', 'FLAVOR': b'numpy', 'TITLE': Empty(dtype=dtype('S1')), 'VERSION': b'2.4', 'block0_items_namebodyparts': b'bodyparts', 'kind': b'string', 'name': b'bodyparts', 'transposed': 1}
Dataset: keypoints/block0_items_level2, Shape: (2,), Data Type: |S1
Attributes: {'CLASS': b'ARRAY', 'FLAVOR': b'numpy', 'TITLE': Empty(dtype=dtype('S1')), 'VERSION': b'2.4', 'block0_items_namecoords': b'coords', 'kind': b'string', 'name': b'coords', 'transposed': 1}
Dataset: keypoints/block0_values, Shape: (12749, 30), Data Type: float64
**********************************************************************
Group: keypoints
Dataset: keypoints/axis0_label0, Shape: (30,), Data Type: int8
Attributes: {'CLASS': b'ARRAY', 'FLAVOR': b'numpy', 'TITLE': Empty(dtype=dtype('S1')), 'VERSION': b'2.4', 'transposed': 1}
Dataset: keypoints/axis0_label1, Shape: (30,), Data Type: int8
Attributes: {'CLASS': b'ARRAY', 'FLAVOR': b'numpy', 'TITLE': Empty(dtype=dtype('S1')), 'VERSION': b'2.4', 'transposed': 1}
Dataset: keypoints/axis0_label2, Shape: (30,), Data Type: int8
Attributes: {'CLASS': b'ARRAY', 'FLAVOR': b'numpy', 'TITLE': Empty(dtype=dtype('S1')), 'VERSION': b'2.4', 'transposed': 1}
Dataset: keypoints/axis0_level0, Shape: (1,), Data Type: |S5
Attributes: {'CLASS': b'ARRAY', 'FLAVOR': b'numpy', 'TITLE': Empty(dtype=dtype('S1')), 'VERSION': b'2.4', 'axis0_namescorer': b'scorer', 'kind': b'string', 'name': b'scorer', 'transposed': 1}
Dataset: keypoints/axis0_level1, Shape: (15,), Data Type: |S10
Attributes: {'CLASS': b'ARRAY', 'FLAVOR': b'numpy', 'TITLE': Empty(dtype=dtype('S1')), 'VERSION': b'2.4', 'axis0_namebodyparts': b'bodyparts', 'kind': b'string', 'name': b'bodyparts', 'transposed': 1}
Dataset: keypoints/axis0_level2, Shape: (2,), Data Type: |S1
Attributes: {'CLASS': b'ARRAY', 'FLAVOR': b'numpy', 'TITLE': Empty(dtype=dtype('S1')), 'VERSION': b'2.4', 'axis0_namecoords': b'coords', 'kind': b'string', 'name': b'coords', 'transposed': 1}
Dataset: keypoints/axis1_label0, Shape: (7,), Data Type: int8
Attributes: {'CLASS': b'ARRAY', 'FLAVOR': b'numpy', 'TITLE': Empty(dtype=dtype('S1')), 'VERSION': b'2.4', 'transposed': 1}
Dataset: keypoints/axis1_label1, Shape: (7,), Data Type: int8
Attributes: {'CLASS': b'ARRAY', 'FLAVOR': b'numpy', 'TITLE': Empty(dtype=dtype('S1')), 'VERSION': b'2.4', 'transposed': 1}
Dataset: keypoints/axis1_label2, Shape: (7,), Data Type: int8
Attributes: {'CLASS': b'ARRAY', 'FLAVOR': b'numpy', 'TITLE': Empty(dtype=dtype('S1')), 'VERSION': b'2.4', 'transposed': 1}
Dataset: keypoints/axis1_level0, Shape: (1,), Data Type: |S12
Attributes: {'CLASS': b'ARRAY', 'FLAVOR': b'numpy', 'TITLE': Empty(dtype=dtype('S1')), 'VERSION': b'2.4', 'axis1_nameNone': b'N.', 'kind': b'string', 'name': b'N.', 'transposed': 1}
Dataset: keypoints/axis1_level1, Shape: (1,), Data Type: |S24
Attributes: {'CLASS': b'ARRAY', 'FLAVOR': b'numpy', 'TITLE': Empty(dtype=dtype('S1')), 'VERSION': b'2.4', 'axis1_nameNone': b'N.', 'kind': b'string', 'name': b'N.', 'transposed': 1}
Dataset: keypoints/axis1_level2, Shape: (7,), Data Type: |S12
Attributes: {'CLASS': b'ARRAY', 'FLAVOR': b'numpy', 'TITLE': Empty(dtype=dtype('S1')), 'VERSION': b'2.4', 'axis1_nameNone': b'N.', 'kind': b'string', 'name': b'N.', 'transposed': 1}
Dataset: keypoints/block0_items_label0, Shape: (30,), Data Type: int8
Attributes: {'CLASS': b'ARRAY', 'FLAVOR': b'numpy', 'TITLE': Empty(dtype=dtype('S1')), 'VERSION': b'2.4', 'transposed': 1}
Dataset: keypoints/block0_items_label1, Shape: (30,), Data Type: int8
Attributes: {'CLASS': b'ARRAY', 'FLAVOR': b'numpy', 'TITLE': Empty(dtype=dtype('S1')), 'VERSION': b'2.4', 'transposed': 1}
Dataset: keypoints/block0_items_label2, Shape: (30,), Data Type: int8
Attributes: {'CLASS': b'ARRAY', 'FLAVOR': b'numpy', 'TITLE': Empty(dtype=dtype('S1')), 'VERSION': b'2.4', 'transposed': 1}
Dataset: keypoints/block0_items_level0, Shape: (1,), Data Type: |S5
Attributes: {'CLASS': b'ARRAY', 'FLAVOR': b'numpy', 'TITLE': Empty(dtype=dtype('S1')), 'VERSION': b'2.4', 'block0_items_namescorer': b'scorer', 'kind': b'string', 'name': b'scorer', 'transposed': 1}
Dataset: keypoints/block0_items_level1, Shape: (15,), Data Type: |S10
Attributes: {'CLASS': b'ARRAY', 'FLAVOR': b'numpy', 'TITLE': Empty(dtype=dtype('S1')), 'VERSION': b'2.4', 'block0_items_namebodyparts': b'bodyparts', 'kind': b'string', 'name': b'bodyparts', 'transposed': 1}
Dataset: keypoints/block0_items_level2, Shape: (2,), Data Type: |S1
Attributes: {'CLASS': b'ARRAY', 'FLAVOR': b'numpy', 'TITLE': Empty(dtype=dtype('S1')), 'VERSION': b'2.4', 'block0_items_namecoords': b'coords', 'kind': b'string', 'name': b'coords', 'transposed': 1}
Dataset: keypoints/block0_values, Shape: (7, 30), Data Type: float64
Attributes: {'CLASS': b'ARRAY', 'FLAVOR': b'numpy', 'TITLE': Empty(dtype=dtype('S1')), 'VERSION': b'2.4', 'transposed': 1}

## Check CSV files

In [34]:
rowsDLC,rowsArr_floatDLC = extract_coordinates(CSVDLC,numx=3,numy=3)
file = open(CSVDLC)
csvreader = csv.reader(file)
np.shape(csvreader)
rowsdl = []

for row in csvreader:
    rowsdl.append(row)

(7, 25)
(4, 22)

In [37]:
df = pd.read_csv(CSVDLCold, header=None)

# Create new rows for each new image with coordinates
new_image_names = [f'img{i:05}.png' for i in range(new_image_count)]  # Replace with actual names

# Prepare new rows
for img_name, coords in zip(new_image_names, new_coordinates.transpose()):
    row = ['labeled-data', 'temp-03192025191735-crop', img_name] + coords.tolist()
    df.loc[len(df)] = row
# Save back to CSV
df.to_csv(CSVDLC, index=False, header=False)

In [38]:
df = pd.read_csv(CSVDLC, header=None)
dfold = pd.read_csv(CSVDLCold, header=None)
print(np.shape(df))
print(np.shape(dfold))

(11907, 25)
(7, 25)

In [49]:
rowsArr_float[rowsArr_float==0]=np.nan